// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getXPtrSFBM
SEXP getXPtrSFBM(std::string path, int n, int m, std::vector<int> p);
RcppExport SEXP _bigsparser_getXPtrSFBM(SEXP pathSEXP, SEXP nSEXP, SEXP mSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(getXPtrSFBM(path, n, m, p));
    return rcpp_result_gen;
END_RCPP
}
// prodVec
NumericVector prodVec(Environment X, const NumericVector& y);
RcppExport SEXP _bigsparser_prodVec(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(prodVec(X, y));
    return rcpp_result_gen;
END_RCPP
}
// cprodVec
NumericVector cprodVec(Environment X, const NumericVector& y);
RcppExport SEXP _bigsparser_cprodVec(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cprodVec(X, y));
    return rcpp_result_gen;
END_RCPP
}
// write_indval
void write_indval(const char * filename, const IntegerVector& i, const NumericVector& x);
RcppExport SEXP _bigsparser_write_indval(SEXP filenameSEXP, SEXP iSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const char * >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    write_indval(filename, i, x);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bigsparser_getXPtrSFBM", (DL_FUNC) &_bigsparser_getXPtrSFBM, 4},
    {"_bigsparser_prodVec", (DL_FUNC) &_bigsparser_prodVec, 2},
    {"_bigsparser_cprodVec", (DL_FUNC) &_bigsparser_cprodVec, 2},
    {"_bigsparser_write_indval", (DL_FUNC) &_bigsparser_write_indval, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bigsparser(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
