# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getXPtrSFBM <- function(path, n, m, p) {
    .Call(`_bigsparser_getXPtrSFBM`, path, n, m, p)
}

prodVec <- function(X, y) {
    .Call(`_bigsparser_prodVec`, X, y)
}

cprodVec <- function(X, y) {
    .Call(`_bigsparser_cprodVec`, X, y)
}

sp_solve_sym_eigen <- function(X, b, add_to_diag, tol, maxiter) {
    .Call(`_bigsparser_sp_solve_sym_eigen`, X, b, add_to_diag, tol, maxiter)
}

write_indval <- function(filename, i, x, offset_p, offset_i = 0L) {
    invisible(.Call(`_bigsparser_write_indval`, filename, i, x, offset_p, offset_i))
}

col_count_sym <- function(p, i) {
    .Call(`_bigsparser_col_count_sym`, p, i)
}

write_indval_sym <- function(filename, p, i, x, offset_p, offset_i = 0L) {
    .Call(`_bigsparser_write_indval_sym`, filename, p, i, x, offset_p, offset_i)
}

