# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getXPtrSFBM <- function(path, n, m, p) {
    .Call(`_bigsparser_getXPtrSFBM`, path, n, m, p)
}

getXPtrSFBM_compact <- function(path, n, m, p, first_i) {
    .Call(`_bigsparser_getXPtrSFBM_compact`, path, n, m, p, first_i)
}

getXPtrSFBM_corr_compact <- function(path, n, m, p, first_i) {
    .Call(`_bigsparser_getXPtrSFBM_corr_compact`, path, n, m, p, first_i)
}

prodVec <- function(X, y) {
    .Call(`_bigsparser_prodVec`, X, y)
}

cprodVec <- function(X, y) {
    .Call(`_bigsparser_cprodVec`, X, y)
}

corr_prodVec <- function(X, y) {
    .Call(`_bigsparser_corr_prodVec`, X, y)
}

corr_cprodVec <- function(X, y) {
    .Call(`_bigsparser_corr_cprodVec`, X, y)
}

sp_solve_sym_eigen <- function(X, b, add_to_diag, tol, maxiter) {
    .Call(`_bigsparser_sp_solve_sym_eigen`, X, b, add_to_diag, tol, maxiter)
}

access_subset <- function(X, ind_row, ind_col) {
    .Call(`_bigsparser_access_subset`, X, ind_row, ind_col)
}

access_subset_compact <- function(X, ind_row, ind_col) {
    .Call(`_bigsparser_access_subset_compact`, X, ind_row, ind_col)
}

access_subset_corr_compact <- function(X, ind_row, ind_col) {
    .Call(`_bigsparser_access_subset_corr_compact`, X, ind_row, ind_col)
}

write_indval <- function(filename, i, x, offset_p, offset_i) {
    invisible(.Call(`_bigsparser_write_indval`, filename, i, x, offset_p, offset_i))
}

col_count_sym <- function(p, i) {
    .Call(`_bigsparser_col_count_sym`, p, i)
}

write_indval_sym <- function(filename, p, i, x, col_count, offset_p, offset_i) {
    .Call(`_bigsparser_write_indval_sym`, filename, p, i, x, col_count, offset_p, offset_i)
}

range_col <- function(p, i) {
    .Call(`_bigsparser_range_col`, p, i)
}

range_col_sym <- function(p, i) {
    .Call(`_bigsparser_range_col_sym`, p, i)
}

write_val_compact <- function(filename, p, i, x, first_i, col_count, offset_p, symmetric) {
    .Call(`_bigsparser_write_val_compact`, filename, p, i, x, first_i, col_count, offset_p, symmetric)
}

write_val_corr_compact <- function(filename, p, i, x, first_i, col_count, offset_p, symmetric) {
    .Call(`_bigsparser_write_val_corr_compact`, filename, p, i, x, first_i, col_count, offset_p, symmetric)
}

