# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getXPtrSFBM <- function(path, n, m, p) {
    .Call(`_bigsparser_getXPtrSFBM`, path, n, m, p)
}

write_indval <- function(filename, i, x) {
    invisible(.Call(`_bigsparser_write_indval`, filename, i, x))
}

